### PR TITLE
Added guest_applications to list of VM attributes collected

### PR DESCRIPTION
**Pull request by pemcg**
The PR adds the guest_applications association to the list of VM attributes collected

### CODE REVIEW

**Comment by pemcg** [comment]
@miq_bot add-label enhancement

**Comment by pemcg** [comment]
@miq_bot add-label ivanchuk/yes

**Comment by pemcg** [comment]
@miq-bot add_label enhancement

**Comment by pemcg** [comment]
@miq-bot add_label ivanchuk/yes

**Comment by pemcg** [comment]
@miq-bot add_label ivanchuk:yes

**Comment by pemcg** [comment]
Would like this backported to Ivanchuk please

**Comment by agrare** [comment]
Hey @pemcg this is a cloud service, it'll be deployed as soon as it is merged, there is no ivanchuk here :)

**Comment by pemcg** [comment]
Good point @agrare !  We mentioned shipping the manifest with an appliance, was anything resolved about this do you know?

**Comment by agrare** [comment]
@pemcg I this is what you're looking for https://github.com/RedHatCloudForms/cfme-migration_analytics/blob/master/config/default-manifest.json

This file here is what CFME cloud-services pulls down before collecting the inventory so that we could dynamically change what we collect without changing the released code.

We should keep these two files in sync as much as possible though so you should update both.

We also are working on allowing a user to apply an updated manifest (https://github.com/RedHatCloudForms/cfme-migration_analytics/issues/27)

**Comment by pemcg** [comment]
Thanks @agrare , I've added https://github.com/RedHatCloudForms/cfme-migration_analytics/pull/32 as well

**Pull request merged**
