### PR TITLE
Enabling filtering by association attribute for the REST API.

### PR DESCRIPTION
**Pull request by abellotti**
- [x] Depends on https://github.com/RedHatInsights/insights-api-common-rails/pull/159

### CODE REVIEW

**Comment by bdunne** [comment]
@abellotti Can you also require the latest insights-api-common v3.9?

**Comment by abellotti** [comment]
Requires build 3.10 of insighs-api-common to pull in: https://github.com/RedHatInsights/insights-api-common-rails/pull/176

**Comment by abellotti** [comment]
Ping @syncrou, just rebased and repushed.  Please take a 👀  Thanks.

**Comment by syncrou** [comment]
@mkanoor could you take a look at this?

**Comment by abellotti** [comment]
Just needed to do what was done with Sources https://github.com/RedHatInsights/sources-api/pull/204/files  so that we're consistent in what we support in the REST API.

**Pull request merged**
